name: Update jdtls
on:
  workflow_dispatch:
  schedule:
    - cron: '13 4 * * *'
  push:
    paths-ignore:
      - "flake.nix"
jobs:
  check-updates:
    name: Update jdtls
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run script
        run: python3 updater.py
      - name: Push updates
        run: |
          git config user.name Github Actions
          git config user.email actions@github.com
          git add flake.nix
          git commit -m "chore: update jdtls"
          git push
          exit 0
